"""Profile the raw SBA dataset without changing it.

Reads `data/raw/SBAnational.csv` as text, writes `artifacts/data/profile.json`,
and regenerates the profile section of `docs/DATA.md` from that JSON. Every
number in that section comes from the JSON, never from hand edits.

Usage:
    uv run python -m creditsense.data.profile
"""

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import pandas as pd

from creditsense.data.checksum import DEFAULT_CHECKSUM_FILE, DEFAULT_RAW_FILE, read_checksum

DEFAULT_PROFILE_FILE = Path("artifacts") / "data" / "profile.json"
DEFAULT_DATA_DOC = Path("docs") / "DATA.md"

STATUS_COLUMN = "MIS_Status"
YEAR_COLUMN = "ApprovalFY"
BLANK_LABEL = "(blank)"

# Columns whose values identify a borrower or lender; value counts are never listed for them.
IDENTIFYING_COLUMNS = frozenset({"LoanNr_ChkDgt", "Name", "City", "Zip", "Bank"})
MAX_LISTED_VALUES = 20

PROFILE_START = "<!-- profile:start (generated by creditsense.data.profile; do not edit) -->"
PROFILE_END = "<!-- profile:end -->"

_KIND_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("integer", re.compile(r"^-?\d+$")),
    ("money", re.compile(r"^\$-?[\d,]+\.\d{2}$")),
    ("date", re.compile(r"^\d{1,2}-[A-Za-z]{3}-\d{2}$")),
)


def load_raw(path: Path) -> pd.DataFrame:
    """Read the raw CSV with every column as text and blanks kept as empty strings."""
    return pd.read_csv(path, dtype=str, keep_default_na=False, encoding="utf-8")


def infer_kind(values: pd.Series) -> tuple[str, int]:
    """Return the dominant value kind of a text column and how many values do not fit it.

    Kinds are checked in order (integer, money, date); a column is labelled with the
    first kind that fits at least 99% of its non-blank values, otherwise `text`.
    """
    stripped = values.str.strip()
    non_blank = stripped[stripped != ""]
    if non_blank.empty:
        return "empty", 0
    for kind, pattern in _KIND_PATTERNS:
        matches = int(non_blank.str.fullmatch(pattern).sum())
        if matches >= 0.99 * len(non_blank):
            return kind, len(non_blank) - matches
    return "text", 0


def _counts(values: pd.Series) -> dict[str, int]:
    labelled = values.str.strip().replace("", BLANK_LABEL)
    counts = labelled.value_counts()
    return {str(k): int(v) for k, v in sorted(counts.items(), key=lambda kv: str(kv[0]))}


def profile_frame(df: pd.DataFrame) -> dict[str, Any]:
    """Build the profile dictionary for a raw SBA frame."""
    columns: list[dict[str, Any]] = []
    for name in df.columns:
        values = df[name]
        blank = int((values.str.strip() == "").sum())
        kind, off_kind = infer_kind(values)
        entry: dict[str, Any] = {
            "name": str(name),
            "kind": kind,
            "off_kind_values": off_kind,
            "blank": blank,
            "distinct": int(values.str.strip().nunique()),
        }
        if name not in IDENTIFYING_COLUMNS and entry["distinct"] <= MAX_LISTED_VALUES:
            entry["value_counts"] = _counts(values)
        columns.append(entry)

    status = df[STATUS_COLUMN].str.strip().replace("", BLANK_LABEL)
    year = df[YEAR_COLUMN].str.strip()
    statuses = sorted(status.unique())
    loans_per_year: dict[str, dict[str, int]] = {
        str(y): dict.fromkeys(statuses, 0) for y in sorted(year.unique())
    }
    for (y, s), n in Counter(zip(year.tolist(), status.tolist(), strict=True)).items():
        loans_per_year[str(y)][str(s)] = n

    return {
        "rows": len(df),
        "columns": len(df.columns),
        "column_profiles": columns,
        "status_counts": _counts(df[STATUS_COLUMN]),
        "non_integer_years": sorted({y for y in year.unique() if not y.isdigit()}),
        "loans_per_approval_year": loans_per_year,
    }


def _code(value: str) -> str:
    """Format a value as inline Markdown code, even if it contains a backtick."""
    return f"`` {value} ``" if "`" in value else f"`{value}`"


def render_profile(profile: dict[str, Any]) -> str:
    """Render the profile as Markdown for `docs/DATA.md`."""
    statuses = sorted(profile["status_counts"])
    lines = [
        PROFILE_START,
        "",
        f"Source: `{profile['source_file']}`, SHA-256 `{profile['source_sha256']}`.",
        "",
        f"- Rows: {profile['rows']:,}",
        f"- Columns: {profile['columns']}",
        "",
        "### Loan status",
        "",
        "| Status | Loans |",
        "| --- | ---: |",
    ]
    lines += [f"| `{s}` | {profile['status_counts'][s]:,} |" for s in statuses]

    lines += [
        "",
        "### Columns",
        "",
        "Kind is inferred from the text values (integer, money, date or text).",
        "Off-kind counts non-blank values that do not fit the kind.",
        "",
        "| Column | Kind | Off-kind | Blank | Distinct |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for c in profile["column_profiles"]:
        lines.append(
            f"| `{c['name']}` | {c['kind']} | {c['off_kind_values']:,} "
            f"| {c['blank']:,} | {c['distinct']:,} |"
        )

    listed = [c for c in profile["column_profiles"] if "value_counts" in c]
    if listed:
        lines += ["", "### Values of low-cardinality columns", ""]
        for c in listed:
            values = ", ".join(f"{_code(k)}: {v:,}" for k, v in c["value_counts"].items())
            lines.append(f"- `{c['name']}`: {values}")

    lines += ["", "### Loans per approval fiscal year", ""]
    if profile["non_integer_years"]:
        odd = ", ".join(f"`{y}`" for y in profile["non_integer_years"])
        lines += [f"Non-integer `{YEAR_COLUMN}` values: {odd}.", ""]
    lines += [
        "| " + " | ".join([YEAR_COLUMN, "Total", *[f"`{s}`" for s in statuses]]) + " |",
        "| --- | " + " | ".join(["---:"] * (len(statuses) + 1)) + " |",
    ]
    for year, counts in profile["loans_per_approval_year"].items():
        total = sum(counts.values())
        cells = [f"{counts.get(s, 0):,}" for s in statuses]
        lines.append("| " + " | ".join([year, f"{total:,}", *cells]) + " |")

    lines += ["", PROFILE_END]
    return "\n".join(lines)


def splice_section(document: str, section: str) -> str:
    """Replace the generated profile section in a document, or append it if missing."""
    start = document.find(PROFILE_START)
    end = document.find(PROFILE_END)
    if start == -1 or end == -1:
        return document.rstrip("\n") + "\n\n" + section + "\n"
    return document[:start] + section + document[end + len(PROFILE_END) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Profile the raw SBA dataset.")
    parser.add_argument("--raw-file", type=Path, default=DEFAULT_RAW_FILE)
    parser.add_argument("--checksum-file", type=Path, default=DEFAULT_CHECKSUM_FILE)
    parser.add_argument("--profile-file", type=Path, default=DEFAULT_PROFILE_FILE)
    parser.add_argument("--data-doc", type=Path, default=DEFAULT_DATA_DOC)
    args = parser.parse_args(argv)

    raw_file: Path = args.raw_file
    if not raw_file.is_file():
        print(f"Raw file not found: {raw_file}", file=sys.stderr)
        return 1

    profile = profile_frame(load_raw(raw_file))
    profile["source_file"] = raw_file.name
    profile["source_sha256"] = read_checksum(args.checksum_file)[0]

    profile_file: Path = args.profile_file
    profile_file.parent.mkdir(parents=True, exist_ok=True)
    profile_file.write_text(
        json.dumps(profile, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )

    data_doc: Path = args.data_doc
    document = data_doc.read_text(encoding="utf-8") if data_doc.is_file() else "# Data\n"
    data_doc.write_text(
        splice_section(document, render_profile(profile)), encoding="utf-8", newline="\n"
    )
    print(f"Wrote {profile_file} and the profile section of {data_doc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
